# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(578, 383)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.checkBoxShowImage = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBoxShowImage.setGeometry(QtCore.QRect(150, 10, 191, 31))
        self.checkBoxShowImage.setStyleSheet("font-size: 24px")
        self.checkBoxShowImage.setObjectName("checkBoxShowImage")
        self.labelImage = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelImage.setGeometry(QtCore.QRect(150, 50, 271, 281))
        self.labelImage.setText("")
        self.labelImage.setPixmap(QtGui.QPixmap("./images/bumlancute.png"))
        self.labelImage.setObjectName("labelImage")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 578, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBoxShowImage.setText(_translate("MainWindow", "Show Image"))
